#!/router/bin/python-2.7.11
import sys
import subprocess
import re
import time

def formattimedelta(deltatime):
    ''' Format Delta time in hours:min:secs'''
    hours, rem = divmod(deltatime, 3600)
    minutes, seconds = divmod(rem, 60)
    return "%02d:%02d:%05.5f" % (int(hours), int(minutes), seconds)

def timethis(method):
    ''' Decorator to measure time of a function '''
    def timethis_wrapper(*args, **kw):
        ''' Time this decorator support wrapper '''
        tstart = time.time()
        result = method(*args, **kw)
        tend = time.time()
        print("Run time(%s %05.5f seconds)"%(formattimedelta(tend - tstart), tend - tstart))
        return result
    return timethis_wrapper

cmd_discover='''
    for i in $(find %s -type f -print ); do
        file $i | grep "ELF 64-bit LSB shared object" | grep "interpreter" | grep "for GNU/Linux" >/dev/null && echo "$i"
    done
'''


cmd='''
    for i in $(find %s -type f -print ); do
        file $i | grep "ELF 64-bit LSB shared object" | grep "interpreter" | grep "for GNU/Linux" >/dev/null && echo -n "$(basename $i) "
    done
'''

@timethis
def compile(x):
    return re.compile(x)

if __name__ == "__main__":
    if sys.argv[1] == "-d":
        dodiscover = True
        sys.argv.pop(1)
    else:
        dodiscover = False
    wsp = sys.argv[1]
    p = sys.argv[2]
    print("WSROOT: %s, PATH: %s" % (wsp, p))
    print("DISCOVER: %s" % (dodiscover))
    checkpath = sys.argv[3] if len(sys.argv) > 3 else None
    if checkpath:
        print("Checking path: %s"% (checkpath))
    fp = "%s/%s"%(wsp,p)
    if dodiscover:
        print("Discovering 64bit ony executables: %s" % (fp))
        cmd_discover = cmd_discover % (fp)
        print(subprocess.check_output(cmd_discover, shell=True))
        exit(0)

    cmd = cmd % (fp)
    x = subprocess.check_output(cmd, shell=True)
    x = x.strip()
    x= x.split()
    x = '|'.join(re.escape(i).replace('\/','/').replace('\_','_') for i in x)

    r = "%s/(%s)"%(re.escape(p).replace('\/','/').replace('\_','_'),x)
    r = r.replace(re.escape(wsp).replace('\/','/').replace('\_','_'),"{{WSROOT_RE}}")
    print(r)
    c = compile(r)
    if checkpath:
        print("Match: %s" % (c.match(checkpath)))

